version: '3.9'
services:
  db:
    container_name: baza_postgre
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Admin1234
    volumes:
      - postgreSQLData:/var/lib/postgresql/data

  pgadmin:
    container_name: postgre_admin  
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgAdmin:/var/lib/pgadmin

  app:
    build: './API'
    container_name: Backend
    volumes:
      - ./API:/BoardGame_Backend
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 --noreload"  
    ports:
      - "8000:8000"

    environment:
      - POSTGRES_HOST=baza_postgre
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Admin1234
      
    depends_on:
      - db

  angular: # name of the first service
    container_name: Frontend
    build: 
      context: './BoardGameFrontend'
      dockerfile: dockerfile

    command:  sh -c "ng serve --host 0.0.0.0 --proxy-config proxy.conf.json"
    ports:
      - 4200:4200
    volumes:
            - './BoardGameFrontend:/BoardGame_Frontend'
    depends_on:
      - db
      - app
   
volumes:
  postgreSQLData:
  pgAdmin:
  BoardGame_Backend:
  Recomendation_Service:
  BoardGame_Frontend:


    #recomendation:
  #  build: 
  #      './Recomendations'
  #  volumes:
  #    - ./Recomendations:/Recomendation_Service
  #  environment:
  #    - POSTGRES_HOST=baza_postgre
  #    - POSTGRES_NAME=postgres
  #    - POSTGRES_USER=user
  #    - POSTGRES_PASSWORD=Admin1234

  #  depends_on:
  #    - db
  #    - app
