version: '3.9'
services:
  db:
    container_name: baza_postgre
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Admin1234
    volumes:
      - postgreSQLData:/var/lib/postgresql/data

  pgadmin:
    container_name: postgre_admin  
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgAdmin:/var/lib/pgadmin

  app:
    build: './API'
    container_name: BoardGame_Service
    volumes:
      - ./API:/BoardGame_Service
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 --noreload"  
    ports:
      - "8000:8000"

    environment:
      - POSTGRES_HOST=baza_postgre
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Admin1234
      
    depends_on:
      - db

  recomendation:
    build: 
        './Recomendations'
    volumes:
      - ./Recomendations:/Recomendation_Service
    environment:
      - POSTGRES_HOST=baza_postgre
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Admin1234

    depends_on:
      - db
      - app

  angular: # name of the first service
    container_name: angularcontainer
    build: 
      context: './BoardGameFrontend'
      dockerfile: dockerfile
    ports:
      - 4200:4200
    volumes:
            - './BoardGameFrontend:/app'
            - '/app/node_modules'
    depends_on:
      - db
      - app
    #working_dir: ./BoardGameFrontend
    command: sh -c "npm i && ng serve --host 0.0.0.0 --disable-host-check"
   

volumes:
  postgreSQLData:
  pgAdmin:
  BoardGame_Service:
  Recomendation_Service:
  BoardGame_Frontend: